
apm-server:
  host: "apm_server_container:8200"

auth:
  secret_token: ''

output.elasticsearch:
  hosts: 'http://elasticsearch_container:9200'
  enabled: true
  protocol: "http"
  username: "elastic"
  password: "admin1234"
  ssl.enabled: false

monitoring.enabled: true

monitoring.elasticsearch:
  protocol: "http"
  username: "elastic"
  password: "admin1234"
  hosts: 'http://elasticsearch_container:9200'