heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: jobber-api-gateway
    name: Jobber API Gateway Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4000/gateway-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-notification
    name: Jobber Notification Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4001/notification-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-auth
    name: Jobber Auth Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4002/auth-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-users
    name: Jobber Users Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4003/user-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-gigs
    name: Jobber Gigs Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4004/gig-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-chat
    name: Jobber Chat Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4005/chat-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-orders
    name: Jobber Orders Service
    schedule: '@every 5s'
    hosts: ["http://192.168.0.42:4006/order-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: jobber-reviews
    name: Jobber Reviews Service
    schedule: '@every 5s'
    urls: ["http://192.168.0.42:4007/review-health"]
    check.request.method: GET
    check.response.status: [200]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
  username: 'elastic'
  password: 'admin1234'