apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete